global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          instance: 'prometheus-server'
          environment: 'monitoring'

      - targets: ['10.0.0.40:9100']
        labels:
          instance: 'web-server-1'
          environment: 'production'

      - targets: ['10.0.2.235:9100']
        labels:
          instance: 'web-server-2'
          environment: 'production'
